### ISSUE TITLE
SplineMonolith name change

### ISSUE THREAD

**Issue by lhaegel** [mach3-software/MaCh3#54]
For the following files, the first letter of the file name should not be capitalised. It should be modified as: 
```
mv MaCh3_core/splines/SplineMonolith.h MaCh3_core/splines/splineMonolith.h
mv MaCh3_core/splines/SplineMonolith.cpp MaCh3_core/splines/splineMonolith.cpp
```

This is currently creating issue for the compilation, and the library must be recompiled to be used for MaCh3_DUNE.

**Comment by KSkwarczynski** [comment]
This is fixed in `develop ` for whole discussion see this thread:
https://t2k-experiment.slack.com/archives/C06EM0C6D7W/p1712827301937439
